[package]
name = "gb_emu"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(prefixed_opcode)'] }


[build-dependencies]
serde_json = "1.0.143"
serde = {version = "1.0.219", features = ["derive"]}